<a href="https://colab.research.google.com/github/Jagannath8/GoeduHub-Training/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **GO_STP_579 -> Jagannath Pal**

# ***Assignment_4***

---


1. Import the numpy package under the name np and Print the numpy version and the configuration 


In [2]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None




---



2. Create a null vector of size 10

In [3]:
import numpy as np
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]




---



3. Create Simple 1-D array and check type and check data types in array


In [4]:
a = np.array([1,2,3,4,5])
print(a.dtype)
print(type(a))

int64
<class 'numpy.ndarray'>




---



4. How to find number of dimensions, bytes per element and bytes of memory used?

In [5]:
c = np.array([[1,2,3], [10,20,30]])
print("Dimension: ", c.ndim)
print("Size of the array: ", c.size)
print("Memory size of one array element in bytes: ", c.itemsize)
print("Memory size of numpy array in bytes:", c.size * c.itemsize)

Dimension:  2
Size of the array:  6
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 48




---



5. Create a null vector of size 10 but the fifth value which is 1


---



In [6]:
x1 = np.zeros(10, dtype = int)
x1[4]=1
print(x1)

[0 0 0 0 1 0 0 0 0 0]




---



6. Create a vector with values ranging from 10 to 49


In [7]:
np.arange(10, 49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])



---



7. Reverse a vector (first element becomes last)


In [8]:
arr = np.arange(1, 10)
print(arr)
print(arr[::-1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]




---



8. Create a 3x3 matrix with values ranging from 0 to 8


In [9]:
matrix = np.arange(0, 9)
matrix.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])



---



9. Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
li =  [1,2,0,0,4,0]
arr = np.array(li)
li_new = list(np.nonzero(arr)[0]+1) 
print("The non zero index are:", li_new)

The non zero index are: [1, 2, 5]




---



10. Create a 3x3 identity matrix

In [11]:
identity = np.identity(3)
print('3x3 matrix:')
print(identity)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]




---



11. Create a 3x3x3 array with random values


In [12]:
rand = np.random.random((3,3,3))
print(rand)

[[[0.64334948 0.7195514  0.40042182]
  [0.61799027 0.50935301 0.02094398]
  [0.79864927 0.73208846 0.5774041 ]]

 [[0.56303534 0.60734271 0.59960112]
  [0.27617786 0.31535429 0.90364957]
  [0.12798399 0.5341098  0.97019192]]

 [[0.61884148 0.51243388 0.68624487]
  [0.67216004 0.11475884 0.77584008]
  [0.89868916 0.04784408 0.80474741]]]




---



12. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
rand1 = np.random.random((10,10))
print(rand1)
print("Minimum:", rand1.min())
print("Minimum:", rand1.max())

[[0.73526766 0.61206464 0.23878468 0.28364466 0.81713374 0.1726653
  0.7585965  0.94686751 0.70206854 0.98679309]
 [0.20751021 0.10122837 0.36420293 0.47949946 0.94492549 0.87725822
  0.05343667 0.68204525 0.47504818 0.04244601]
 [0.75346693 0.28575717 0.83359386 0.55695024 0.89019643 0.85157128
  0.05075558 0.30268349 0.95567639 0.36810339]
 [0.62708515 0.19143832 0.78449937 0.66899869 0.99756291 0.16365936
  0.72629212 0.28647736 0.7553017  0.95033891]
 [0.07916212 0.09595313 0.07093148 0.57191188 0.38148484 0.51027691
  0.65801224 0.15320849 0.19278678 0.2838837 ]
 [0.46766654 0.56087635 0.24890614 0.65132484 0.14044388 0.32820851
  0.57103664 0.6028706  0.57747773 0.5678836 ]
 [0.42529032 0.63133228 0.50566431 0.19370993 0.18388204 0.59690129
  0.42246549 0.08768447 0.80385115 0.78158742]
 [0.81052115 0.50433827 0.88014704 0.13312401 0.34501529 0.71831995
  0.02622765 0.59013388 0.30035718 0.45601409]
 [0.08603948 0.52577233 0.44901388 0.4380446  0.75001812 0.02913081
  0.5196275  



---



13. Create a random vector of size 30 and find the mean value

In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5470782373332874




---



14. Create a 2d array with 1 on the border and 0 inside

In [15]:
ar = np.ones((10,10))
ar[1:-1, 1:-1] = 0
print(ar)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]




---



15. How to add a border (filled with 0's) around an existing array? 

In [16]:
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]




---




16. How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [17]:
import numpy as np
arr1 = np.arange(1,15).reshape(2,7)
print(arr1)

# get 13
arr1[1,-2]

# replace 13 by 20
print('Before replacing :\n', arr1)
arr1[1,-2] = 20
print('\nAfter replacing :\n', arr1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Before replacing :
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

After replacing :
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [18]:
#get first row only
arr1[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
#get 3rd column only
arr1[:,2]

array([ 3, 10])

In [20]:
# get [2, 4, 6],
arr1[0,1::2]

array([2, 4, 6])



---



17. How to Convert a 1D array to a 2D array with 2 rows

In [21]:
k = np.array([[1,2,3], [10,20,30]])
k.reshape(2,3)

array([[ 1,  2,  3],
       [10, 20, 30]])



---



18. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])

Desired Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [27]:
pattern = np.array([1,2,3])
print(pattern)
pattern = np.append(np.repeat(pattern,3),np.tile(pattern,3))
print(pattern)

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]




---



19. Write a program to show how Numpy taking less memory compared to Python List?

In [23]:
import sys
l = range(1000)
b=10
print(sys.getsizeof(b))
print("Memory in list:", sys.getsizeof(b)*len(l))

b1 = np.arange(1000)
print("Memory in numpy:", b1.size*b1.itemsize)

28
Memory in list: 28000
Memory in numpy: 8000




---



20. Write a program to show how Numpy taking less time compared to Python List?

In [24]:
import sys
import time

size = 1000000
l1=range(size)
l2=range(size)

n1=np.arange(size)
n2=np.arange(size)

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Time taken in list:", (time.time()-start)*1000)

start = time.time()
result1=n1+n2
print("Time taken in numpy:", (time.time()-start)*1000)

Time taken in list: 136.75284385681152
Time taken in numpy: 4.689216613769531




---

